### ISSUE TITLE
[Block/Nonblock] 그림이 잘못된거 같아요

### ISSUE THREAD

**Issue by kyupid** [tmdgusya/roach-wiki-issue#2]
내용: http://roach-wiki.com/doku.php?id=block#async_nonblocking

설명해주신 Block 그림이 좀 헷갈리는데요.
제가 생각했덤 Block 은 아래와 같아요.

1. 클->스레드(서버) Done?
2. 그냥 하염없이 기다림
3. 스레드->클 Done~~

크롬 데브툴 네트워크에서 status pending  상태가 2번이라고 생각했어요
근제 그림이 스레드로부터 "아직이야~~~" 라는 응답을 받고
또 물어보는 방식이라 제가 잘못이해하고 있었나싶어서 궁금합니다

## 잘못됐다고 생각하는 그림

![image](https://user-images.githubusercontent.com/59721293/162353130-0c32748f-0b0e-4241-8028-3a679c84995e.png)

## 내가 의도하는 그림

![image](https://user-images.githubusercontent.com/59721293/162353226-e78b1288-c5bd-4fd3-b61f-6c848d4e3037.png)

**Comment by tmdgusya** [comment]
C 언어에서 wait 관련된 코드인데요

```c
#define wake_up(x)                  __wake_up(x, TASK_NORMAL, 1, NULL)          
#define wake_up_nr(x, nr)           __wake_up(x, TASK_NORMAL, nr, NULL)         
#define wake_up_all(x)              __wake_up(x, TASK_NORMAL, 0, NULL)          
#define wake_up_locked(x)           __wake_up_locked((x), TASK_NORMAL, 1)       
#define wake_up_all_locked(x)       __wake_up_locked((x), TASK_NORMAL, 0)       
                                                                                
#define wake_up_interruptible(x)    __wake_up(x, TASK_INTERRUPTIBLE, 1, NULL)   
#define wake_up_interruptible_nr(x, nr)   __wake_up(x, TASK_INTERRUPTIBLE, nr, NULL)
#define wake_up_interruptible_all(x)      __wake_up(x, TASK_INTERRUPTIBLE, 0, NULL)                                                                  
#define wake_up_interruptible_sync(x)     __wake_up_sync((x), TASK_INTERRUPTIBLE)

/**                                                                             
 * __wake_up - wake up threads blocked on a waitqueue.                          
 * @wq_head: the waitqueue                                                      
 * @mode: which threads                                                         
 * @nr_exclusive: how many wake-one or wake-many threads to wake up             
 * @key: is directly passed to the wakeup function                              
 *                                                                              
 * If this function wakes up a task, it executes a full memory barrier before   
 * accessing the task state.                                                    
 */                                                                             
void __wake_up(struct wait_queue_head *wq_head, unsigned int mode,                                                                                   
                  int nr_exclusive, void *key)                                  
{                                                                               
      __wake_up_common_lock(wq_head, mode, nr_exclusive, 0, key);               
}    
```

**Comment by tmdgusya** [comment]
설명을 읽어보니 요청을 보낸(Client) 가 들어와서 wait 하고 있으면 누군가 와서 wake_up 을 시켜줘야 한다는거 같아요.
큐의 설명이 맞는거 같네요 ㅎㅎ 해당 이미지로 수정하겠습니다.

**Comment by tmdgusya** [comment]
Kyu 말이 맞는거 같아요. 
그래서 NonBlocking Socket 에서 보면 Client 가 응답이 오기전까지 Block 되지만 곧바로 NonBlocking Socket 에서 예외를 리턴해줘서 Blocking 되지않고 클라이언트가 작업할 수 있는거 같아요.

**Comment by tmdgusya** [comment]
덕분에 좀 더 NonBlocking 구조를 만드는 법에 대해서도 생각해볼 수 있었네요

**Comment by kyupid** [comment]
> 그래서 NonBlocking Socket 에서 보면 Client 가 응답이 오기전까지 Block 되지만 곧바로 NonBlocking Socket 에서 예외를 리턴해줘서 Blocking 되지않고 클라이언트가 작업할 수 있는거 같아요.

그렇군요!! Nonblocking 도 어쨋든 무시하고 지나가는게 아니라 예외를 리턴해줘야 Blocking 되지 않는거군요..!
C는 잘모르겠지만 설명하시는거 느낌은 알겠습니다!

근데 여기서 C가 튀어나오는게 서버가 예를들어 톰캣 일때 C가 나오는 부분은 어디일까요?
톰캣에서 통신할때 JNI 같은 것을 사용하는건가요?

**Comment by tmdgusya** [comment]
네 어찌 됐던 결과를 리턴해줘야 Client 가 진행할 수 있으니까요 ㅎㅎ
NonBlock 자체의 개념도 그렇기도 하고

**Comment by tmdgusya** [comment]
서버가 톰캣일때는 잘 모르겠어요. 자바랑 상관없이 그냥 C 의 코드를 들고온거에요 ㅎㅎ

**Comment by tmdgusya** [comment]
C 의 NonBlocking Socket 을 보면 Buffer 에 넣어두고 Client 가 Poll(질의) 를 할때 예외를 리턴해줘요.
예외이름이 뭐였지 기억은 안나는데.. 하여튼 검색하시면 나올겁니다.
